### ISSUE TITLE
can u help me plz....

### ISSUE THREAD

**Issue by cLood4io** [hilch/demo-MpCnc-with-mapp-motion#1]
Needed module arsvcreg of required range from V4.25 up to all higher versions not installed.	427

I TRY TO USE A X20 AND ACOPOS DRIVE BUT ALWAYS I GET THIS ERROR I SERACH IN THE ENTERNET BUT i didn't find anything,,,,,
soryy i put this problem can you plz help me ,,,

**Comment by hilch** [comment]
unfortunately I can not provide support via GitHub. Please contact you local B&R office.
Regarding your problem: please try to change Automation Runtime version. All library should then be exchanged with the right version.
